#!/bin/bash
#src_path=$1
#dst_path=$2
#file_path=$3

file=$(basename "$3") #Obtenim el nom del fitxer
src_full_path="$1/$file" #Obtenim el path absolut del fitxer origen

dst_full_path="$2/$3" #Obtenim el path absolut del fitxer desti
rm "$dst_full_path" #Eliminem el fitxer desti

ln -s "$src_full_path" "$dst_full_path" #Creem el soft link
