#!/bin/bash

if [ $n -ne 2]
then 
	echo "Falten arguments"
	exit 1

elif [ ! -f $1 ]
then
	echo "El primer argument ha de ser un fitxer"
	exit 2

elif [ ! -f $2 ]
then
	echo "El segon argument ha de ser un fitxer"
	exit 3

else
	vimdiff $1 $2
fi
